### ISSUE TITLE
Can't build Android version

### ISSUE THREAD

**Issue by dslamnig** [margaretmz/segmentation-style-transfer#19]
ColorSpaceType not found. Tried many versions of tensorflow libraries, always the same failure. App crashes after taking a picture.

[...]
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.e2etflite.segmentation_and_style_transfer, PID: 31987
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tensorflow/lite/support/image/ColorSpaceType;
        at org.tensorflow.lite.task.vision.segmenter.OutputType$1.createMasksFromBuffer(OutputType.java:74)
        at org.tensorflow.lite.task.vision.segmenter.ImageSegmenter.segment(ImageSegmenter.java:224)
        at org.tensorflow.lite.task.vision.segmenter.ImageSegmenter.segment(ImageSegmenter.java:176)
        at com.e2etflite.sample.backgroundstylizer.ui.segmentation.SegmentationAndStyleTransferViewModel.cropPersonFromPhoto(SegmentationAndStyleTransferViewModel.kt:113)
        at com.e2etflite.sample.backgroundstylizer.ui.segmentation.SegmentationAndStyleTransferFragment$onViewCreated$1.invokeSuspend(SegmentationAndStyleTransferFragment.kt:193)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.tensorflow.lite.support.image.ColorSpaceType" on path: DexPathList[[zip file "/data/app/com.e2etflite.segmentation_and_style_transfer-LymZPOPdqyQVEYQ9JNYlRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.e2etflite.segmentation_and_style_transfer-LymZPOPdqyQVEYQ9JNYlRA==/lib/arm, /data/app/com.e2etflite.segmentation_and_style_transfer-LymZPOPdqyQVEYQ9JNYlRA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
[,,,]

**Comment by amindadgar** [comment]
It seems the crash is happening in coroutine scope in the file _SegmentationAndStyleTransferViewModel.kt line 113_ . Share the code causing the problem, I may help you.

**Comment by dslamnig** [comment]
I'm trying to build the project as cloned, no modifications. The code is in the repo.
Since the Android build is based mostly on nightly TensorFlow builds, maybe org.tensorflow.lite.support.image.ColorSpaceType class was moved to another package, or removed.

**Comment by amindadgar** [comment]
After hours of struggling with versions I got no success too.
I've seen this issue in library repo and I tried the answer but I got no success. I'll attach the link below it maybe help you.
https://github.com/tensorflow/tensorflow/issues/30755

**Comment by margaretmz** [comment]
The error is due to a mismatch in the version for the TFlite Support library which is used by the other libraries such as the task API. Try the following:

- Invalidate caches / Restart Android Studio
- Add `implementation('org.tensorflow:tensorflow-lite-support:0.0.0-nightly') { changing = true }` to make sure you have the latest tflite support library.

**Comment by hdk24** [comment]
used latest tflite support library implementation("org.tensorflow:tensorflow-lite-support:0.1.0")
[https://github.com/tensorflow/tflite-support/releases/](https://github.com/tensorflow/tflite-support/releases/)

**Comment by ridoy-ai** [comment]
For everyone visiting the thread, please use latest tflite support library to solve the issue, I used:
implementation("org.tensorflow:tensorflow-lite-support:0.2.0")
